sqlfluff:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: random
      user: "{{ env_var('USER') }}"
      password: "{{ env_var('USER') }}"
      role: "{{ env_var('USER') }}"
      warehouse: "{{ env_var('USER') }}"
      database: "{{ env_var('USER') }}"
      schema: analytics
      query_tag: "{{ env_var('USER') }}"
      threads: 32
      client_session_keep_alive: False