# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: SQLFluff lint

on:
  push:

jobs:
  sqlfluffbuild:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install sqlfluff==0.4.0.a3 dbt==0.18
    - name: setup dbt
      run: |
        mkdir ~/.dbt
        cp profiles.yml ~/.dbt/profiles.yml
        dbt deps
    - name: Lint sqlfluff
      run: sqlfluff lint models
